services:
  jupyterhub:
    build: .
    image: jupyterhub-custom
    container_name: jupyterhub-container
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./templates:/srv/jupyterhub/templates
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - jupyterhub_data:/srv/jupyterhub/data
      - ./logService.py:/srv/jupyterhub/logService.py
    #  - ./studentContainers/courses/course1:/studentContainers/courses/course1
    ports:
      - "8533:8000"
    networks:
      - jupyterhub
    extra_hosts:
      - "host.docker.internal:127.17.0.1"
  db:
    image: mongo:latest
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=loggedData
      - $MONGO_INITDB_ROOT_USERNAME=ranDumUs8er99991
      - $MONGO_INITDB_ROOT_PASSWORD=randomPassWord99919
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - ./mongodbvolume:/data/db
    networks: 
      - jupyterhub

volumes:
  jupyterhub_data:

networks:
  jupyterhub:
    name: jupyterhub